### ISSUE TITLE
lost the fence

### ISSUE THREAD

**Issue by DoaIbu999** [twisted89/Manor-Lords-Save-Load-Mod#4]
hello, i have problem after loading the game, all the residents house doesn't have fences

![Manor Lords   5_8_2023 3_33_30 PM](https://user-images.githubusercontent.com/132883674/236765754-43b18772-721d-49cb-a0f4-c592b6e69fc0.png)

**Comment by twisted89** [comment]
Not much I can do about that, the save functionality was clearly not finished and some things will be missing.
